
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-21T14:50:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "87a1a1ab64057e13589e2506078d0100944ba5e6",
 "version": "1.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
